---

- hosts: all
  become: true
  pre_tasks:

  - name: update cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: all
  become: true
  roles:
    - base

- hosts: all
  become: true
  roles:
    - web_servers
